config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/reports')

  resources :email, only: [:create]
  resources :reports
end

app/models/policy_published.rb
class PolicyPublished < ActiveRecord::Base
  belongs_to :report
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :report

  after_save :update_report_counts

  def self.save_dmarc(dmarc)
    report = Report.create(dmarc.metadata)
    report.create_policy_published(dmarc.policy_published)
    dmarc.records.each do |row|
      report.records << Record.create(row)
    end
  end

  def update_report_counts
    report.update_counts if report
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :records
  has_one :policy_published

  def update_counts
    counts = self.records.inject({failed: 0, passed: 0}) do |sum, record|
      key = (record.disposition == 'reject') ? :failed : :passed
      sum[key] = sum[key] + record.count
      sum
    end
    self.update_attributes!({failed_count: counts[:failed], passed_count: counts[:passed]})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate
  protect_from_forgery with: :exception

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    klass.new(object, view_context)
  end

  def authenticate
    if Rails.env.production?
      authenticate_or_request_with_http_basic('Administration') do |username, password|
        username == ENV['SITE_USER'] && password == ENV['SITE_PASS']
      end
    end
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    dmarc = Dmarc::Email.new(params[:message]).report
    return unless dmarc

    Record.save_dmarc(dmarc)

    render text: 'success', status: 200
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.order("created_at desc").page(params[:page])
  end

  def show
    @report = Report.find(params[:id])
    @policy_published = @report.policy_published
    @records = @report.records.order("count desc").page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title_tag(page_title, opts={})
    opts.reverse_merge!(:default_title => APP_NAME)
    content_tag :title, [opts[:default_title], page_title].
      reject { |x| x.to_s.strip.blank? }.
      join(' - ')
  end

  def body_tag(options={}, &block)
    controller_name = controller.controller_path.gsub('/', '-').gsub('_', '-')
    body_class = [controller_name, options[:class]].compact.join(' ')
    body_id = [controller_name, controller.action_name].join('-')

    content_tag(:body, capture(&block), :class => body_class, :id => body_id)
  end

  def nav_link(title, path, options={})
    current_controller = options[:controller] || title.downcase
    controller_name = controller.controller_name
    active = controller_name == current_controller
    content_tag :li, :class => ('active' if active) do
      link_to title, path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <%= title_tag yield(:page_title) %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script>document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/, 'js');</script>
  </head>
  <%= body_tag do %>
    <div class="wrapper">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, :class => "alert alert-#{name == :notice ? 'success' : 'error'}" do %>
          <a class="close" data-dismiss="alert">&times;</a>
          <%= msg %>
        <% end %>
      <%- end -%>

      <%= yield %>

    </div> <!-- div#container -->

    <%= javascript_include_tag 'application' %>
    <%= yield :javascript %>
  <% end %>
</html>

app/views/reports/index.html.erb
<% content_for :page_title, 'Reports' %>

<section>
  <h2>Reports</h2>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>org_name</th>
        <th>begin</th>
        <th>end</th>
        <th>passed</th>
        <th>failed</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= link_to report.id,  report_path(report) %></td>
          <td><%= report.org_name %></td>
          <td><%= report.begin.to_s(:long_ordinal) %></td>
          <td><%= report.end.to_s(:long_ordinal) %></td>
          <td><%= report.passed_count %></td>
          <td><%= report.failed_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pagination">
    <%= paginate @reports %>
  </div>
</section>

app/views/reports/show.html.erb
<% content_for :page_title, "Report ##{@report.id}" %>

<h1><%= link_to "Reports", reports_path %> / #<%= @report.id %></h1>

<section>
  <div class="column-wrapper">
    <div class="report column">
      <h2>Report</h2>
      <dl>
        <% [:org_name, :email, :extra_contact_info, :report_id ].each do |attr| %>
          <dt><%= attr.to_s.humanize %></dt>
          <dd><%= @report.send(attr) %></dd>
        <% end %>
        <dt>begin</dt>
        <dd><%= @report.begin.to_s(:long_ordinal) %></dd>
        <dt>End</dt>
        <dd><%= @report.end.to_s(:long_ordinal) %></dd>
      </dl>
    </div>
    <div class="policy column">
      <h2>Policy Published</h2>
      <dl>
        <% [:domain, :adkim, :aspf, :p, :pct ].each do |attr| %>
          <dt><%= attr.to_s.humanize %></dt>
          <dd><%= @policy_published.send(attr) %></dd>
        <% end %>
      </dl>
    </div>
  </div>
</section>

<section>
  <h2>Records</h2>
  <div class="table-wrapper">
    <table>
      <thead>
        <tr>
          <th>source_ip</th>
          <th>dkim</th>
          <th>count</th>
          <th>disposition</th>
          <th>spf</th>
          <th>reason_type</th>
          <th>comment</th>
          <th>header_from</th>
          <th>dkim_domain</th>
          <th>dkim_result</th>
          <th>dkim_hresult</th>
          <th>spf_domain</th>
          <th>spf_result</th>
        </tr>
      </thead>
      <tbody>
        <% @records.each do |record| %>
          <tr>
            <td><%= record.source_ip %></td>
            <td><%= record.dkim %></td>
            <td><%= record.count %></td>
            <td><%= record.disposition %></td>
            <td><%= record.spf %></td>
            <td><%= record.reason_type %></td>
            <td><%= record.comment %></td>
            <td><%= record.header_from %></td>
            <td><%= record.dkim_domain %></td>
            <td><%= record.dkim_result %></td>
            <td><%= record.dkim_hresult %></td>
            <td><%= record.spf_domain %></td>
            <td><%= record.spf_result %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>
<div class="pagination">
  <%= paginate @records %>
</div>